### ISSUE TITLE
cookbook stagnated?

### ISSUE THREAD

**Issue by sjsadowski** [rigrassm/firewalld-cookbook#21]
@rigrassm there are a slew of pull requests to fix bugs right now, and some outstanding issues.

If noone is bothering to curate this, would you mind turning it over to someone who will? I'm volunteering as I have a vested interest in this for my environment.

**Comment by jayhendren** [comment]
ping @rigrassm 

@sjsadowski looks like [the cookbook is up for adoption on Supermarket](https://supermarket.chef.io/cookbooks/firewalld); you might consider forking the repo and adopting the cookbook on Supermarket

**Comment by RickyGrassmuck** [comment]
@sjsadowski I went ahead and reviewed and merged the open pull requests. The project is up for adoption and I will be happy to transfer it over if you can [adopt it](https://supermarket.chef.io/cookbooks/firewalld/adoption).

**Comment by sjsadowski** [comment]
I don't mind giving it a new home and getting it updated a bit.

**Comment by sjsadowski** [comment]
@rigrassm I applied for adopting the cookbook - let me know if you need anything else from me.

**Comment by RickyGrassmuck** [comment]
@sjsadowski Just sent the tranfer ownership request to you through the Chef Supermarket.

**Comment by sjsadowski** [comment]
@rigrassm Thanks, I accepted it.

**Comment by sjsadowski** [comment]
@rigrassm lmk if you want me to fork this or transfer it - I'd prefer transfer to keep the issues and history intact, but I can move forward either way.

**Comment by RickyGrassmuck** [comment]
I just sent the repo transfer to you. @sjsadowski

**Comment by sjsadowski** [comment]
@rigrassm Thanks very much - I've now transferred the cookbook and completed transfer of this repo.
