### ISSUE TITLE
Adding iptable rules using firewalld_rich_rule

### ISSUE THREAD

**Issue by micmicsuarez** [rigrassm/firewalld-cookbook#24]
This is my previous code and I want to modify it using `firewalld`. We used `firewalld` because we are using `centos 7.2`.

```
%w(all_established all_icmp prefix postfix).each do |rule|
    iptables_rule "#{rule}" do
        action :enable
    end
end
```

How can I implement it again using `firewalld`?

**Comment by RickyGrassmuck** [comment]
Check out the [rich_rule](https://github.com/rigrassm/firewalld-cookbook#rich_rule) section of the README  and if you want to see how the rich_rule provider was implemented you can see the source [here](https://github.com/rigrassm/firewalld-cookbook/blob/master/providers/rich_rule.rb).
